        !COMPILER-GENERATED INTERFACE MODULE: Thu Jul 16 14:19:49 2015
        MODULE SUB_INVERSE_MATRIX__genmod
          INTERFACE 
            SUBROUTINE SUB_INVERSE_MATRIX(MATRIX,N)
              INTEGER(KIND=4) :: N
              REAL(KIND=8), INTENT(INOUT) :: MATRIX(N,N)
            END SUBROUTINE SUB_INVERSE_MATRIX
          END INTERFACE 
        END MODULE SUB_INVERSE_MATRIX__genmod
