        !COMPILER-GENERATED INTERFACE MODULE: Thu Jul 16 14:19:50 2015
        MODULE SUB_OVERLAP_HALF_POSITIVE__genmod
          INTERFACE 
            SUBROUTINE SUB_OVERLAP_HALF_POSITIVE(N_BASIS,OVERLAP_AO,    &
     &OVERLAP_HALF,TRANS_OVERLAP_HALF)
              INTEGER(KIND=4), INTENT(IN) :: N_BASIS
              REAL(KIND=8), INTENT(IN) :: OVERLAP_AO(N_BASIS,N_BASIS)
              REAL(KIND=8), INTENT(INOUT) :: OVERLAP_HALF(N_BASIS,      &
     &N_BASIS)
              REAL(KIND=8), INTENT(INOUT) :: TRANS_OVERLAP_HALF(N_BASIS,&
     &N_BASIS)
            END SUBROUTINE SUB_OVERLAP_HALF_POSITIVE
          END INTERFACE 
        END MODULE SUB_OVERLAP_HALF_POSITIVE__genmod
