
clean:
	cd overlap; make clean
all:
	cd overlap; make
install:
	cd overlap; make install
	cp ./overlap/main_overlap_slater.exe ../../bin/main_overlap_slater.exe
	cp ./overlap/main_overlap_slater.exe .


